const data = [
{image: "hulu-image-one.jpeg", link: "https://press.hulu.com/news/2022/02/15/disneys-onyx-collective-and-abc-news-acquire-award-winning-documentary-aftershock-following-its-sundance-premiere/", head: "FEBRUARY 15, 2022", body: `Disney’s Onyx Collective and ABC News acquire award-winning documentary ‘Aftershock.’ Following its Sundance premiere.`},
{image: "hulu-image-two.png", link: "https://press.hulu.com/news/2022/01/21/20th-digital-studios-bite-size-halloween-shorts-expanding-to-feature-length-horror-slate-at-hulu/", head: "JANUARY 21, 2022", body: `20th Digital Studio’s “Bite Size Halloween” Shorts Expanding To Feature-Length Horror Slate At Hulu`},
{image: "hulu-image-three.jpeg", link: "https://press.hulu.com/news/2022/01/10/disneys-onyx-collective-orders-the-plot-limited-series-executive-produced-and-starring-two-time-oscar%e2%93%a1-winner-mahershala-ali-from-endeavor-content-abby-ajayi-to-a/", head: "JANUARY 10, 2022", body: `Disney’s Onyx Collective Order ’The Plot’ Limited Series, Executive Produced And Starring Two-Time Oscar Winner Mahershala Ali From Endeavor Content, Abby Ajayi To Adapt From The Best-Selling Novel By Jean Hand Korelitz`},
{image: "hulu-image-four.jpeg", link: "https://press.hulu.com/news/2021/12/16/year-with-hulu-2021-its-in-your-dna/", head: "DECEMBER 16, 2021", body: `Year With Hulu 2021: It's In Your DNA`},
{image: "hulu-image-five.png", link: "https://press.hulu.com/news/2021/11/17/hulu-launches-new-online-shopping-destination-featuring-original-merchandise-hulu-branded-swag-and-limited-edition-ugly-holiday-sweaters/", head: "NOVEMBER 17, 2021", body: `Hulu Launches New Online Shopping Destination Featuring Original Merchandise, Hulu Branded Swag, and Limited Edition Ugly Holiday Sweaters`},
{image: "hulu-image-six.png", link: "https://press.hulu.com/news/2021/10/01/hulu-is-being-haunted-by-an-evil-spirit-as-2021-huluween-hub-is-revealed/", head: "OCTOBER 1, 2021", body: `Hulu Is Being Haunted By An Evil Spirit As 2021 Huluween Hub Is Revealed`},
{image: "hulu-image-seven.jpeg", link: "https://press.hulu.com/news/2021/09/28/hulu-and-uber-eats-announce-partnership-to-give-eligible-hulu-subscribers-six-months-of-complimentary-uber-eats-pass/", head: "SEPTEMBER 28, 2021", body: `Hulu and Uber Eats Announce Partnership to Give Eligible Hulu Subscribers Six Months of Complimentary Uber Eats Pass`},
{image: "hulu-image-two.png", link: "https://press.hulu.com/news/2021/08/31/vivo-indian-premier-league-icc-mens-t20-world-cup-and-bcci-cricket-coming-soon-to-espn-hotstar-specials-available-on-hulu-beginning-sept-1/", head: "AUGUST 31, 2021", body: `VIVO Indian Premier League, ICC Men’s T20 World Cup, and BCCI Cricket Coming Soon to ESPN+, Hotstar Specials Available on Hulu Beginning Sept. 1`},
{image: "hulu-image-nine.jpeg", link: "https://press.hulu.com/news/2021/08/06/hulu-presents-at-the-2021-television-critics-association-summer/", head: "AUGUST 6, 2021", body: `Hulu Presents Upcoming Original Series ‘Dopesick,’ ‘The Great’ Season Two, ‘Only Murders In The Building’ And ‘Nine Perfect Strangers’ At The 2021 Television Critics Association Summer Press Tour`},
{image: "hulu-image-ten.jpeg", link: "https://press.hulu.com/news/2021/07/29/hulu-is-the-exclusive-streaming-partner-for-lollapalooza-2021/", head: "JULY 29, 2021", body: `Hulu is the Exclusive Streaming Partner for Lollapalooza 2021`},
{image: "hulu-image-eleven.png", link: "https://press.hulu.com/news/2021/07/29/hulu-adds-nfl-network-to-hulu-live-tv-channel-line-up/", head: "JULY 29, 2021", body: `Hulu Adds NFL Network to Hulu + Live TV Channel Line-Up`},
{image: "hulu-image-twelve.png", link: "https://press.hulu.com/news/2021/07/13/hulus-haha-awards-return-for-a-second-year-with-new-laugh-out-loud-shows-categories-and-nominees/", head: "JULY 13, 2021", body: `Hulu’s HAHA Awards Return for Second Year with New Laugh-Out-Loud Shows, Categories, and Nominees`}
]

export default data